use std::{env, fmt::Write, fs, path};

use heck::{AsPascalCase, ToUpperCamelCase};
use walkdir::WalkDir;

fn walk<P: AsRef<path::Path>, F>(
    dir: P,
    start_with: Option<&str>,
    code: &mut String,
    module_name: Option<&str>,
    gen_enum: bool,
    filter: Option<F>,
) where
    F: Fn(&str) -> bool,
{
    if let Some(module_name) = module_name {
        code.write_fmt(format_args!(
            "#[allow(unused)] pub(crate) mod {module_name} {{ use dioxus::prelude::*; use strum::*; use serde::{{Deserialize, Serialize}}; "
        ))
        .unwrap();
    }

    let mut variants = vec![];

    for entry in WalkDir::new(dir) {
        let entry = entry.unwrap();

        if !entry.path().is_file() || !entry.path().extension().is_some_and(|x| x == "png" || x == "svg") {
            continue;
        }

        if let Some(start_with) = start_with {
            let Some(file_name) = entry.path().file_name().and_then(|x| x.to_str()) else {
                continue;
            };

            if !file_name.starts_with(start_with) {
                continue;
            }
        }

        if let Some(filter) = filter.as_ref()
            && !filter(entry.file_name().to_str().unwrap())
        {
            continue;
        }

        let stem = entry.path().file_stem().unwrap().to_str().unwrap().to_ascii_uppercase();
        let relative = entry.path().to_string_lossy().replace("\\", "/");

        code.write_fmt(format_args!(
            "#[allow(unused)] pub(crate) const {stem}: dioxus::prelude::Asset = dioxus::prelude::asset!(\"{relative}\"); "
        ))
        .unwrap();

        variants.push((
            entry
                .path()
                .file_stem()
                .unwrap()
                .to_str()
                .unwrap()
                .to_upper_camel_case(),
            stem,
        ));
    }

    if gen_enum && let Some(module_name) = module_name {
        code.write_fmt(format_args!(
            "#[allow(unused)] #[derive(Clone, Copy, PartialEq, Eq, Debug, Serialize, Deserialize, EnumString, VariantArray)] #[strum(serialize_all = \"lowercase\")] pub(crate) enum {} {{ ", AsPascalCase(module_name)
        )).unwrap();

        for variant in &variants {
            code.write_fmt(format_args!("{}, ", variant.0)).unwrap();
        }

        code.write_fmt(format_args!("}}")).unwrap();

        code.write_fmt(format_args!(
            "impl From<{0}> for Asset {{ fn from(value: {0}) -> Self {{ match value {{",
            AsPascalCase(module_name)
        ))
        .unwrap();

        for variant in variants {
            code.write_fmt(format_args!(
                "{}::{} => {}, ",
                AsPascalCase(module_name),
                variant.0,
                variant.1
            ))
            .unwrap();
        }

        code.write_fmt(format_args!("}} }} }}")).unwrap();
    }

    if module_name.is_some() {
        code.write_fmt(format_args!("}}")).unwrap();
    }
}

fn main() {
    println!("cargo::rerun-if-changed=assets");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = path::Path::new(&out_dir).join("assets.rs");

    let mut code = String::from("// Generated by build.rs\n\n");

    walk(
        "assets/extracted/avatar",
        None,
        &mut code,
        None,
        false,
        Some(|_x: &str| true),
    );
    walk(
        "assets/extracted/emoji",
        Some("sns_emoji"),
        &mut code,
        None,
        false,
        Some(|_x: &str| true),
    );

    walk(
        "assets/icons",
        None,
        &mut code,
        Some("icons"),
        false,
        Some(|_x: &str| true),
    );

    walk(
        "assets/extracted/sticker/game",
        None,
        &mut code,
        Some("stickers"),
        true,
        Some(|x: &str| x.chars().count() == 21),
    );

    fs::write(dest.clone(), code).unwrap();

    std::process::Command::new("rustfmt")
        .arg(&dest)
        .status()
        .expect("failed to run rustfmt");
}
