use std::{env, fmt::Write, fs, path};

use walkdir::WalkDir;

fn walk<P: AsRef<path::Path>>(dir: P, start_with: Option<&str>, code: &mut String) {
    for entry in WalkDir::new(dir) {
        let entry = entry.unwrap();

        if !entry.path().is_file() || !entry.path().extension().is_some_and(|x| x == "png") {
            continue;
        }

        if let Some(start_with) = start_with {
            if !entry.path().starts_with(start_with) {
                continue;
            }
        }

        let stem = entry.path().file_stem().unwrap().to_str().unwrap().to_ascii_uppercase();
        let relative = entry.path().to_string_lossy().replace("\\", "/");

        code.write_fmt(format_args!(
            "#[allow(unused)] pub(crate) const {stem}: Asset = asset!(\"{relative}\");\n"
        ))
        .unwrap();
    }
}

fn main() {
    println!("cargo::rerun-if-changed=assets");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = path::Path::new(&out_dir).join("assets.rs");

    let mut code = String::from("// Generated by build.rs\n\n");

    walk("assets/extracted/avatar", None, &mut code);
    walk("assets/extracted/emoji", Some("sns_emoji"), &mut code);

    fs::write(dest, code).unwrap();
}
