use std::{env, fmt::Write, fs, path};

use walkdir::WalkDir;

fn main() {
    println!("cargo::rerun-if-changed=assets");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = path::Path::new(&out_dir).join("assets.rs");

    let mut code = String::from("// Generated by build.rs\n\n");

    for entry in WalkDir::new("assets/extracted/avatar") {
        let entry = entry.unwrap();

        if !entry.path().is_file() || !entry.path().extension().is_some_and(|x| x == "png") {
            continue;
        }

        let stem = entry.path().file_stem().unwrap().to_str().unwrap().to_ascii_uppercase();
        let relative = entry.path().to_string_lossy().replace("\\", "/");

        code.write_fmt(format_args!(
            "pub(crate) const {stem}: Asset = asset!(\"{relative}\");\n"
        ))
        .unwrap();
    }

    fs::write(dest, code).unwrap();
}
